import { makeStyles } from '@material-ui/core/styles';

//
export default makeStyles((theme) => ({
  slider: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
  },
  title: {
    position: 'absolute',
    top: '40%',
    fontWeight: '300',
    fontSize: '40px',
    letterSpacing: '3px',
    [theme.breakpoints.down('sm')]: {
      top: '43%',
      marginLeft: '12px',
      fontSize: '18px',
    },
  },
  paragraph: {
    position: 'absolute',
    top: '55%',
  },
  whiteButton: {
    color: 'white',
    border: '1px solid white',
  },
  'left-arrow': {
    position: 'absolute',
    top: '45%',
    left: '20px',
    fontSize: '1rem',
    zIndex: '10',
    cursor: 'pointer',
    userSelect: 'none',
    color: 'white',
    backgroundColor: '#2161d6',
    borderRadius: '100%',
    transform: 'scale(1.8)',
  },
  'right-arrow': {
    position: 'absolute',
    top: '45%',
    right: '20px',
    fontSize: '1rem',
    zIndex: '10',
    cursor: 'pointer',
    userSelect: 'none',
    color: 'white',
    backgroundColor: '#2161d6',
    borderRadius: '100%',
    transform: 'scale(1.8)',
  },
  slide: {
    width: '100vw',
    height: '70vh',
    display: 'none',
    transitionDuration: '2s ease',
    backgroundSize: 'cover',
    backgroundAttachment: 'fixed',
    backgroundRepeat: 'no-repeat',
    [theme.breakpoints.down('sm')]: {
      backgroundPosition: '60% 50%',
    },
    transition: 'background-image 0.5s linear',
  },
  colorOverlay: {
    position: 'absolute',
    top: '0',
    left: '0',
    width: '100%',
    height: '100%',
    backgroundColor: 'black',
    opacity: '0.6',
    zIndex: '10',
  },

  'slide-active': {
    transitionDuration: '2s',
    display: 'block',
    transform: 'scale(1)',
  },
  dot: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    border: '3px solid #f1f1f1',
    margin: '0 5px',
    background: '#f1f1f1',
    cursor: 'pointer',
  },
  'dot-active': {
    background: 'rgb(32, 32, 32)',
  },
  'container-dots': {
    position: 'absolute',
    bottom: '10px',
    left: '50%',
    transform: 'translateX(-50%)',
    display: 'flex',
  },
}));
